import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { Badge } from "@/components/Badge";
import { DashboardNav } from "@/components/dashboard/DashboardNav";
import { SectionHeader } from "@/components/SectionHeader";
import { DeleteTestManagementButton } from "@/components/test-management/DeleteTestManagementButton";
import { getCurrentUser } from "@/lib/auth";
import { formatEnumLabel } from "@/lib/issueOptions";
import { canDeleteRelease, canEditRelease, canExportRelease, canViewReleases } from "@/lib/permissions";
import { getReleaseReadiness } from "@/lib/releaseReadiness";
import { coverageLabels, requirementReference } from "@/lib/requirements";

type Props={params:Promise<{id:string}>};
function Metric({label,value,accent="text-ivory"}:{label:string;value:string|number;accent?:string}){return <article className="rounded-lg border border-bronze bg-clay p-4 shadow-card"><p className="text-sm text-beige">{label}</p><p className={`mt-2 font-display text-2xl font-bold tabular-nums ${accent}`}>{value}</p></article>}
export default async function ReleaseDetailPage({params}:Props){const user=await getCurrentUser();if(!user)redirect("/login");if(!canViewReleases(user))redirect("/dashboard");const id=Number((await params).id);if(!Number.isInteger(id))notFound();const data=await getReleaseReadiness(id);if(!data)notFound();const {release,requirements,metrics,readiness,unresolved}=data;return <main className="min-h-screen bg-espresso text-ivory"><DashboardNav user={user}/><section className="mx-auto max-w-7xl px-5 pb-20 pt-32 sm:px-8">
  <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><SectionHeader eyebrow={`QA Release RL-${String(id).padStart(4,"0")} · ${formatEnumLabel(release.status)}`} title={release.name} description={release.description||"A focused QA readiness record."}/><div className="flex flex-wrap gap-3">{canExportRelease(user)&&<a href={`/api/releases/${id}/report`} download className="rounded-full border border-amber px-5 py-3 text-sm font-bold text-amber transition hover:bg-amber hover:text-espresso">Export CSV</a>}{canEditRelease(user,release)&&<Link href={`/dashboard/releases/${id}/edit`} className="rounded-full bg-coral px-5 py-3 text-sm font-bold text-espresso">Edit Release</Link>}<Link href="/dashboard/releases" className="rounded-full border border-bronze px-5 py-3 text-sm font-bold">Back to Releases</Link></div></div>
  <section className={`mt-8 rounded-lg border p-5 shadow-card sm:p-6 ${readiness==="READY"?"border-sage/40 bg-sage/10":readiness==="AT_RISK"?"border-amber/40 bg-amber/10":"border-ember/40 bg-ember/10"}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-beige">Computed QA assessment</p><h2 className="mt-2 font-display text-3xl font-bold">{formatEnumLabel(readiness)}</h2></div><Badge label={readiness}/></div><p className="mt-4 max-w-4xl text-sm leading-6 text-beige">{readiness==="READY"?"All scoped Requirements are passing, all associated executions are complete and passed, and no unresolved defects remain.":readiness==="AT_RISK"?"Required coverage and execution are complete, but unresolved non-critical defects remain and should be reviewed before shipping.":"One or more hard blockers remain: missing release scope or runs, incomplete coverage, failed/blocked/not-run execution, or an unresolved Critical defect."}</p><p className="mt-2 text-xs text-beige">This is a QA assessment from IssueFlow records, not a claim that the software is production-ready.</p></section>
  <div className="mt-6 grid gap-4 grid-cols-2 md:grid-cols-4 xl:grid-cols-6"><Metric label="Test Runs" value={metrics.runs}/><Metric label="Executions" value={metrics.executions}/><Metric label="Passed" value={metrics.PASSED} accent="text-sage"/><Metric label="Failed" value={metrics.FAILED} accent="text-[#ff9aa2]"/><Metric label="Blocked" value={metrics.BLOCKED} accent="text-amber"/><Metric label="Not Run" value={metrics.NOT_RUN}/><Metric label="Pass Rate" value={`${metrics.passRate}%`} accent="text-sage"/><Metric label="Open Defects" value={metrics.openDefects} accent="text-coral"/><Metric label="Critical" value={metrics.criticalDefects} accent="text-[#ff9aa2]"/><Metric label="High" value={metrics.highDefects} accent="text-coral"/><Metric label="Reopened" value={metrics.reopenedDefects} accent="text-amber"/><Metric label="Requirements" value={requirements.length}/></div>
  <div className="mt-8 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><section className="overflow-hidden rounded-lg border border-bronze bg-clay shadow-card"><div className="border-b border-bronze p-5"><h2 className="font-display text-xl font-semibold">Requirement Coverage</h2><p className="mt-1 text-sm text-beige">Release-specific results use only executions from associated Test Runs.</p></div>{requirements.length===0?<p className="p-5 text-sm text-beige">No Requirements are in scope. Edit this Release to define what QA must verify.</p>:<div className="divide-y divide-bronze/70">{requirements.map(requirement=><div key={requirement.id} className="p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><Link href={`/dashboard/requirements/${requirement.id}`} className="min-w-0 font-semibold text-ivory transition hover:text-coral [overflow-wrap:anywhere]">{requirementReference(requirement.id)} · {requirement.title}</Link><Badge label={requirement.coverage}/></div><p className="mt-2 text-sm text-beige">{requirement.feature_module} · {coverageLabels[requirement.coverage]} · {requirement.testCases.length} Test Case{requirement.testCases.length===1?"":"s"}</p></div>)}</div>}</section><section className="overflow-hidden rounded-lg border border-bronze bg-clay shadow-card"><div className="border-b border-bronze p-5"><h2 className="font-display text-xl font-semibold">Open Defects</h2><p className="mt-1 text-sm text-beige">Distinct unresolved defects linked through associated release executions or currently scoped Test Cases.</p></div>{unresolved.length===0?<p className="p-5 text-sm text-beige">No unresolved defects are linked to this Release.</p>:<div className="divide-y divide-bronze/70">{unresolved.map(issue=><Link key={issue.id} href={`/dashboard/issues/${issue.id}`} className="block p-5"><span className="font-semibold [overflow-wrap:anywhere]">IF-{String(issue.id).padStart(4,"0")} · {issue.title}</span><span className="mt-3 flex gap-2"><Badge label={issue.severity}/><Badge label={issue.status}/></span></Link>)}</div>}</section></div>
  <section className="mt-8 overflow-hidden rounded-lg border border-bronze bg-clay shadow-card"><div className="border-b border-bronze p-5"><h2 className="font-display text-xl font-semibold">Associated Test Runs</h2><p className="mt-1 text-sm text-beige">Run snapshots remain historical records; current Requirement links are shown separately above.</p></div>{release.runs.length===0?<p className="p-5 text-sm text-beige">No Test Runs are associated. Edit this Release to connect existing execution history.</p>:<div className="divide-y divide-bronze/70">{release.runs.map(run=>{const passed=run.executions.filter(item=>item.status==="PASSED").length;const failed=run.executions.filter(item=>item.status==="FAILED").length;const incomplete=run.executions.filter(item=>item.status==="NOT_RUN").length;return <Link key={run.id} href={`/dashboard/test-runs/${run.id}`} className="grid gap-3 p-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center"><div className="min-w-0"><p className="font-semibold [overflow-wrap:anywhere]">TR-{String(run.id).padStart(4,"0")} · {run.suite_name}</p><p className="mt-1 text-sm text-beige">{run.release_label} · {run.environment}</p></div><p className="text-sm text-beige">{passed} passed · {failed} failed · {incomplete} not run</p></Link>})}</div>}</section>
  <section className="mt-8 rounded-lg border border-bronze bg-clay p-5 shadow-card"><h2 className="font-display text-xl font-semibold">Readiness rules</h2><div className="mt-4 grid gap-3 text-sm leading-6 text-beige md:grid-cols-3"><p><strong className="text-[#ff9aa2]">Not Ready:</strong> no scoped Requirements or runs, incomplete/non-passing coverage, failed/blocked/not-run execution, or unresolved Critical defect.</p><p><strong className="text-amber">At Risk:</strong> hard blockers are clear, but one or more unresolved lower-severity defects remain.</p><p><strong className="text-sage">Ready:</strong> all scoped Requirements pass, every execution passes, and no unresolved defects remain.</p></div></section>
  {canDeleteRelease(user,release)&&<div className="mt-8 rounded-lg border border-ember/30 bg-clay p-5"><p className="mb-4 text-sm text-beige">Admin-only: deleting this QA Release disconnects its Test Runs but preserves their execution history.</p><DeleteTestManagementButton endpoint={`/api/releases/${id}`} returnTo="/dashboard/releases" label="Release"/></div>}
  </section></main>}
